#!/usr/bin/env python3
"""
debug_mapping_viz.py
可视化验证 QC_REF 和 QC_MD_MAP 之间的权重映射一致性。

功能：
1. [终端] 输出详细的原子匹配对照表 (MD Name <-> REF Name)。
2. [文件] 生成 *_DEBUG_OVERLAY.pdb，将 MD 原子通过 Kabsch 算法叠合到 REF 上。
   - Chain A: REF 原子 (绿色)
   - Chain B: MD 原子 (红色, 已叠合)
"""

import os
import glob
import numpy as np
from scipy.spatial.distance import cdist

class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    CYAN = '\033[96m'
    RESET = '\033[0m'

def read_pdb_weights_and_coords(pdb_file):
    """读取 PDB，返回权重 > 0.001 的原子列表"""
    weighted_atoms = []
    try:
        with open(pdb_file, 'r') as f:
            for line in f:
                if line.startswith("ATOM") or line.startswith("HETATM"):
                    try:
                        # 假设权重(B-factor)在 60-66 列
                        b_factor_str = line[60:66].strip()
                        if not b_factor_str: continue
                        val = float(b_factor_str)
                        if val > 0.001:
                            x = float(line[30:38])
                            y = float(line[38:46])
                            z = float(line[46:54])
                            atom_name = line[12:16].strip()
                            res_name = line[17:20].strip()
                            res_id = line[22:26].strip()
                            weighted_atoms.append({
                                'val': val,
                                'coord': np.array([x, y, z]),
                                'name': atom_name,
                                'resname': res_name,
                                'resid': res_id,
                                'line': line.strip()
                            })
                    except ValueError: continue
    except Exception as e:
        print(f"Error reading {pdb_file}: {e}")
        return []
    return weighted_atoms

def kabsch_superimpose(ref_coords, mov_coords):
    """
    计算旋转矩阵和平移向量，将 mov_coords 叠合到 ref_coords
    返回: (rotated_mov_coords, rmsd)
    """
    # 1. 计算质心
    ref_center = np.mean(ref_coords, axis=0)
    mov_center = np.mean(mov_coords, axis=0)
    
    # 2. 移到原点
    ref_centered = ref_coords - ref_center
    mov_centered = mov_coords - mov_center
    
    # 3. 计算协方差矩阵
    H = np.dot(mov_centered.T, ref_centered)
    
    # 4. SVD 分解
    U, S, Vt = np.linalg.svd(H)
    
    # 5. 计算旋转矩阵 R
    R = np.dot(Vt.T, U.T)
    
    # 6. 处理反射情况 (Det(R) < 0)
    if np.linalg.det(R) < 0:
        Vt[2, :] *= -1
        R = np.dot(Vt.T, U.T)
        
    # 7. 应用旋转和平移
    rotated_coords = np.dot(mov_centered, R) + ref_center
    
    # 8. 计算 RMSD
    diff = rotated_coords - ref_coords
    rmsd = np.sqrt(np.mean(np.sum(diff**2, axis=1)))
    
    return rotated_coords, rmsd

def save_overlay_pdb(filename, ref_atoms_subset, md_atoms_subset, rotated_md_coords):
    """保存叠合后的 PDB 用于 PyMOL 查看"""
    with open(filename, 'w') as f:
        f.write("REMARK    GENERATED BY DEBUG_MAPPING_VIZ.PY\n")
        f.write("REMARK    CHAIN A: REFERENCE (FIXED)\n")
        f.write("REMARK    CHAIN B: MD SUBSET (ALIGNED)\n")
        
        # 写入 REF (Chain A)
        for i, atom in enumerate(ref_atoms_subset):
            # 构造简单的 PDB 行
            x, y, z = atom['coord']
            # ATOM/HETATM, Serial, Name, AltLoc, ResName, Chain, ResSeq
            f.write(f"ATOM  {i+1:5d} {atom['name']:^4s} {atom['resname']:3s} A{atom['resid']:>4s}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00 {atom['val']:6.2f}           {atom['name'][0]}\n")
            
        # 写入 MD (Chain B) - 使用变换后的坐标
        offset = len(ref_atoms_subset)
        for i, atom in enumerate(md_atoms_subset):
            x, y, z = rotated_md_coords[i]
            f.write(f"ATOM  {offset+i+1:5d} {atom['name']:^4s} {atom['resname']:3s} B{atom['resid']:>4s}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00 {atom['val']:6.2f}           {atom['name'][0]}\n")
        f.write("END\n")

def check_subset_pair(ref_file, md_file, output_dir):
    cid = os.path.basename(ref_file).replace("_QC_REF.pdb", "")
    print(f"\n{Colors.CYAN}>>> Checking pair: {cid}{Colors.RESET}")
    print(f"   REF: {os.path.basename(ref_file)}")
    print(f"   MD : {os.path.basename(md_file)}")
    
    ref_atoms = read_pdb_weights_and_coords(ref_file)
    md_atoms = read_pdb_weights_and_coords(md_file)
    
    if not ref_atoms or not md_atoms:
        print(f"   {Colors.RED}[FAIL] No weighted atoms found.{Colors.RESET}")
        return False

    # 贪心匹配逻辑
    matched_ref_indices = []
    md_indices = []
    used_ref_indices = set()
    
    # 用于显示的表格数据
    match_table = []
    
    print(f"\n   {Colors.YELLOW}[Matching Process Log]{Colors.RESET}")
    print(f"   {'MD Atom':<15} | {'Val':<8} <==> {'REF Atom':<15} | {'Val':<8} | {'Diff':<8}")
    print(f"   {'-'*70}")

    match_success = True

    for i, md_atom in enumerate(md_atoms):
        best_j = -1
        min_diff = 1.0
        
        for j, ref_atom in enumerate(ref_atoms):
            if j in used_ref_indices: continue
            
            diff = abs(md_atom['val'] - ref_atom['val'])
            if diff < min_diff:
                min_diff = diff
                best_j = j
                
        if best_j != -1 and min_diff < 0.02:
            matched_ref_indices.append(best_j)
            md_indices.append(i)
            used_ref_indices.add(best_j)
            
            ref_atom = ref_atoms[best_j]
            
            # 记录表格
            md_label = f"{md_atom['name']}({md_atom['resname']})"
            ref_label = f"{ref_atom['name']}({ref_atom['resname']})"
            
            # 检查名称是否不一致（提示潜在错位）
            name_status = ""
            if md_atom['name'] != ref_atom['name']:
                name_status = f"{Colors.RED}<- NAME MISMATCH!{Colors.RESET}"
            
            print(f"   {md_label:<15} | {md_atom['val']:.4f}   {Colors.GREEN}<-->{Colors.RESET}   {ref_label:<15} | {ref_atom['val']:.4f}   | {min_diff:.4f} {name_status}")
            
        else:
            print(f"   {md_atom['name']:<15} | {md_atom['val']:.4f}   {Colors.RED}<-->   [NO MATCH FOUND]{Colors.RESET}")
            match_success = False
            
    if not match_success:
        print(f"\n   {Colors.RED}[FAIL] Could not match all MD atoms to REF.{Colors.RESET}")
        return False

    # 提取坐标
    subset_ref_coords = np.array([ref_atoms[j]['coord'] for j in matched_ref_indices])
    subset_md_coords = np.array([md_atoms[i]['coord'] for i in md_indices])
    
    subset_ref_atoms = [ref_atoms[j] for j in matched_ref_indices]
    subset_md_atoms = [md_atoms[i] for i in md_indices]

    # 计算 3D 叠合 (Superposition)
    rotated_md_coords, rmsd = kabsch_superimpose(subset_ref_coords, subset_md_coords)
    
    # 几何验证 (距离矩阵差异)
    dmat_ref = cdist(subset_ref_coords, subset_ref_coords)
    dmat_md = cdist(subset_md_coords, subset_md_coords)
    dist_diff = np.abs(dmat_ref - dmat_md)
    max_geo_diff = np.max(dist_diff)
    
    print(f"\n   {Colors.YELLOW}[Geometry Check]{Colors.RESET}")
    print(f"   -> Internal Geometry Max Diff: {max_geo_diff:.4f} A")
    print(f"   -> Superposition RMSD:         {rmsd:.4f} A")

    # 生成叠合 PDB
    overlay_filename = os.path.join(output_dir, f"{cid}_DEBUG_OVERLAY.pdb")
    save_overlay_pdb(overlay_filename, subset_ref_atoms, subset_md_atoms, rotated_md_coords)
    print(f"   -> Visualization saved:        {os.path.basename(overlay_filename)}")
    print(f"      (Open in PyMOL: Chain A=REF, Chain B=MD)")

    if max_geo_diff < 0.4 and rmsd < 0.5:
        print(f"\n   {Colors.GREEN}[PASS] Mapping Verified.{Colors.RESET}")
        return True
    else:
        print(f"\n   {Colors.RED}[FAIL] Geometry or RMSD too high! Check '{overlay_filename}' for details.{Colors.RESET}")
        return False

def main():
    root_dir = "./data/qc_structures"
    if not os.path.exists(root_dir): 
        print(f"Directory not found: {root_dir}")
        return
    
    ref_files = glob.glob(os.path.join(root_dir, "*_QC_REF.pdb"))
    ref_files.sort()
    
    if not ref_files:
        print("No *_QC_REF.pdb files found.")
        return

    print(f"{Colors.GREEN}>>> Starting Subset Mapping Visualizer...{Colors.RESET}")
    
    for ref_path in ref_files:
        cid = os.path.basename(ref_path).replace("_QC_REF.pdb", "")
        md_path = os.path.join(root_dir, f"{cid}_QC_MD_MAP.pdb")
        
        if os.path.exists(md_path):
            check_subset_pair(ref_path, md_path, root_dir)

if __name__ == "__main__":
    main()